name: hero_application
description: Applcation for view heros.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version
version: 1.0.0+1

# Environment
environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Firebase
  cloud_firestore: ^2.2.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_storage: ^8.1.3

  # File Picker
  file_picker: ^3.0.2+2

  # Provider
  provider: ^5.0.0

  # Text Animator
  animated_text_kit: ^4.2.1

  # Awesome dialog
  awesome_dialog: ^2.1.0

  # Country Picker
  country_picker: ^2.0.5

  # Future Progress Dialog
  future_progress_dialog: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter Specifications
flutter:

  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: LobsterTwo-Regular
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
